name: Build and Push to Docker Hub

on:
  push

env:
  REGISTRY_NAME: docker.io
  REGISTRY_IMAGE: saferdns
  REGISTRY_USER: gr00vysky
  IMAGE_VERSION: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux]
        arch: [386,amd64]
        
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to registry
      run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login $REGISTRY_NAME -u $REGISTRY_USER --password-stdin
          echo "manifest_cmd=docker manifest create $REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION" >> $GITHUB_ENV
  
    - name: Build image and manifest
      run: |
          docker build --build-arg "OS=${{ matrix.os }}" --build-arg "ARCH=${{ matrix.arch }}" -t "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION-${{ matrix.arch }}" . 
          docker push "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION-${{ matrix.arch }}"
          echo "manifest_cmd=${{ env.manifest_cmd }} --amend $REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION-${{ matrix.arch }}" >> $GITHUB_ENV


    - name: Push image
      run: |
          echo "${{ env.manifest_cmd }}"
          "${{ env.manifest_cmd }}"
          docker manifest push "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION"