name: Build and Push to Docker Hub

on:
  push

env:
  REGISTRY_NAME: docker.io
  REGISTRY_IMAGE: saferdns
  REGISTRY_USER: gr00vysky
  CORE_VERSION: v1.9.4
  CORE_CHECKSUM: 3356e1f795dddf067d69aff08cd3142763e8ead040c65d93994b6de3156f15a4
  IMAGE_OS: linux
  IMAGE_ARCHS: linux/386,linux/amd64

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
        
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to registry
      run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login $REGISTRY_NAME -u $REGISTRY_USER --password-stdin
  
    - name: Build and push image
      run: |
          docker buildx build \
          --push \
          --build-arg "VERSION=$CORE_VERSION" \
          --build-arg "CHECKSUM=$CORE_CHECKSUM" \
          --platform "$IMAGE_ARCHS" \
          --tag "$REGISTRY_USER/$REGISTRY_IMAGE:$CORE_VERSION" .