name: Build and Push to Docker Hub

on:
  push

env:
  REGISTRY_NAME: docker.io
  REGISTRY_IMAGE: saferdns
  REGISTRY_USER: gr00vysky
  IMAGE_VERSION: latest
  IMAGE_OS: linux
  IMAGE_ARCHS: 386,amd64

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
        
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to registry
      run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login $REGISTRY_NAME -u $REGISTRY_USER --password-stdin
  
    - name: Build and push image
      run: |
          IFS=',' read -ra archs <<< "$IMAGE_ARCHS"
          for arch in "$archs"; do
            docker build --platform "$IMAGE_OS/$arch" --build-arg "OS=$IMAGE_OS" --build-arg "ARCH=$arch" -t "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION-$arch" . 
            docker push "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION-${{ matrix.arch }}"
          done

    - name: Create and push manifest
      run: |
          for i in $(docker images "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION" --format "{{.Repository}}:{{.Tag}}")
          do
            echo $i
            out="$out --amend $i"
          done
          out="docker manifest create $REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION $out"
          echo $out
          $out
          docker manifest push "$REGISTRY_USER/$REGISTRY_IMAGE:$IMAGE_VERSION"