name: Download and store Blocklists

on:
  schedule:
    - cron: '0 3 */7 * *'

env:
  TMP_DIR: temp

jobs:
  store-blocklists:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
          sudo apt update && \
          sudo apt install subversion && \
          mkdir "$TMP_DIR" && \
          mkdir -p $GITHUB_WORKSPACE/blocklists/hosts

    - name: Get Ultimate Hosts Blacklist
      continue-on-error: true
      run: |
          cd "$TMP_DIR" && \
          svn checkout https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/trunk/hosts && \
          cat hosts/* > $GITHUB_WORKSPACE/blocklists/hosts/Ultimate.Hosts.Blacklist.txt
  
    - name: Cleanup
      run: |
          rm -rf "$TMP_DIR"

    - name: Publishing the changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add .
        git commit -m $(date +%F)
        git push