name: Download and store Blocklists

on:
  push

env:
  TMP_DIR: temp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
        
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
          sudo apt update && \
          sudo apt install subversion && \
          mkdir "$TMP_DIR"

    - name: Get Ultimate Hosts Blacklist
      run: |
          cd "$TMP_DIR" && \
          svn checkout https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/trunk/hosts && \
          cat hosts/* > Ultimate.Hosts.Blacklist.txt
          && pwd
  